# -*- coding: utf-8 -*-
"""huggingface.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1RiLRxD_5GwpIJyGJ4CIc2wHn7txSlrEI
"""



!pip install diffusers transformers accelerate scipy safetensors

import torch
from diffusers import StableDiffusionPipeline
import matplotlib.pyplot as plt

from diffusers import StableDiffusionPipeline
import torch
import matplotlib.pyplot as plt

# Load the model (no login needed for public models)
pipe = StableDiffusionPipeline.from_pretrained(
    "runwayml/stable-diffusion-v1-5"
    # Removed torch_dtype=torch.float16 as it's typically for GPU
).to("cpu") # Changed device to "cpu"

prompt = "A futuristic city skyline at sunset, with flying cars, glowing neon lights, and tall skyscrapers made of glass and steel, in a vibrant cyberpunk art style"
image = pipe(prompt).images[0]

# Show the image
plt.imshow(image)
plt.axis("off")
plt.title("Prompt: " + prompt)
plt.show()